### ISSUE TITLE
Use date-fns library

### ISSUE THREAD

**Issue by souporserious** [deseretdigital/dayzed#10]
First, just wanted to say this is a wonderful little abstraction for calendars in React! 🎉 I was curious if you would be willing to swap out similar functions with [date-fns](https://github.com/date-fns/date-fns) where it makes sense? I think it could reduce bundle sizes for others utilizing the `date-fns` library and hopefully it would keep this one a similar size since each function can be imported individually. If this sounds ok, I'd be willing to submit a PR, just let me know 😇

**Comment by mkartchner994** [comment]
Yes, I would be willing to swap out the `./src/utils.js` functions that make sense. PRs are definitely welcome.

Thanks for taking interest in the lib!

**Comment by mkartchner994** [comment]
I think this has been done in scope of this pull request - https://github.com/deseretdigital/dayzed/pull/17.

If there was more to this you would like to see, please reopen this issue. Thanks!

**Comment by souporserious** [comment]
Wonderful!!! Sorry I never got around to doing this, glad someone was able to do it though! 🎉
