### ISSUE TITLE
Sunday is not (necessarily) the first day of the week.

### ISSUE THREAD

**Issue by donavon** [deseretdigital/dayzed#13]
> An array containing an array of date objects for each week of the month. **Starting from Sunday to Saturday**.

What about locales where the week starts on Monday–most of Europe, for example? Is there a way to specify this?

**Comment by mkartchner994** [comment]
That is a great point! There isn't currently a way to specify this. For my use case I only needed it to start on Sunday so I hadn't thought about that. I would be open to a PR to add the ability to specify what day of the week to start. I personally wont be able to work on adding something like this for a couple weeks.

**Comment by mkartchner994** [comment]
This is now in https://github.com/deseretdigital/dayzed/releases/tag/v2.1.0
