### ISSUE TITLE
Option to see "outside days" (days outside the current month)

### ISSUE THREAD

**Issue by adrienharnay** [deseretdigital/dayzed#21]
Hey,

It would be nice to provide the feature (maybe via a prop) to see days outside of the month, and being able to select them. Basically, the same thing react-dates is providing:

http://airbnb.io/react-dates/?selectedKind=DRP%20-%20Calendar%20Props&selectedStory=with%20outside%20days%20enabled&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Would you be open to a PR?

Thanks in advance!

**Comment by mkartchner994** [comment]
Hello @adrienharnay!

Yes, I am open to a PR that adds this functionality via a prop, so as not to break backwards compatibility 👍 

Thanks for taking interest in the project!

**Comment by mkartchner994** [comment]
This is now in https://github.com/deseretdigital/dayzed/releases/tag/v2.1.0
Thanks @donysukardi!
