### ISSUE TITLE
Proposal: Turn components in examples into reusable components

### ISSUE THREAD

**Issue by donysukardi** [deseretdigital/dayzed#24]
Currently the library only exposes Dayzed component. What if we turn all the components in examples into reusable ones, i.e. RangeDatePicker, MultiDatePicker, DatePicker, while still exposes the render props to userland?

**Comment by mkartchner994** [comment]
I like the idea, but I am wondering if this would be better served as the goal of a different project that uses the Dayzed component under the hood. I am concerned that if we add the different Datepicker components, the Dayzed component's upgrade path would become tightly coupled with the other Datepickers making it more difficult to add new ideas to Dayzed when they come up.

I think Dayzed could be useful for more than just Datepickers. For example, It could also be used to create a custom google calendar like layout which doesn't deal with selecting specific dates, but showing events on those days instead.

Thoughts?

**Comment by donysukardi** [comment]
You bring up a really good point. We could definitely maintain the components as a separate project.

Do you mind if I create a new library out of https://github.com/deseretdigital/dayzed/pull/25 then?
Any suggestion for the package name? `dayzed-pickers`?

**Comment by mkartchner994** [comment]
Yes, if you would like to create the new lib that would be great! `dayzed-pickers` sounds good to me 👍
