### ISSUE TITLE
Provide option to go forward/backward a variable number of months

### ISSUE THREAD

**Issue by samhh** [deseretdigital/dayzed#28]
Hi there, love the library!

What I'm working on at the moment requires me to provide the option to move forwards or backwards in both monthly increments and yearly increments. Whilst the former is handled natively by the library with `getBackProps` and `getForwardProps`, the latter is not and at present will require me to write my own logic checking dates, something which is otherwise within the library's purview.

I'm not sure exactly how the API should be designed. For example, you could provide an optional property to the aforementioned methods which internally defaults to `1`:

```typescript
<button
  ...getBackProps({ calendars, monthsToIncrement: 12 })
/>
```

---

Also, while I'm here, I've written up some basic TypeScript typings. Are you cool with me putting them up on DefinitelyTyped for other TS users?

Cheers!

**Comment by SamHH** [comment]
Oh, this already exists as `offset`! :smile: Could do with adding to the docs. And the TS question remains.

**Comment by mkartchner994** [comment]
@SamHH Thanks for your interest in the lib! Good point about the docs and offset. It's used in the examples, but not defined in the README. I can look at adding that. Concerning the TS typings, I am open to adding them if you want to provide a PR. Thanks! 👍
