### ISSUE TITLE
Move date-fns to dependencies

### ISSUE THREAD

**Issue by OriR** [deseretdigital/dayzed#30]
I think that `date-fns` should be moved to dependencies as opposed to peer deps and dev deps.

The reason being that it directly uses them internally and doesn't expose an API that consumes them - that's why `react` is defined that way.

**Comment by devinrhode2** [comment]
So, I'm going to have to try out a date-picker that uses react hooks - the kool-aid looks good - 
I install Dayzed and then copy-pasted the usage example.. invoked <Simple /> on a blank page, have date-fns installed, but I'm getting this error:
```
./node_modules/dayzed/dist/dayzed.esm.js
Module not found: Can't resolve 'date-fns/add_days' in '/Users/dr2/my-project/node_modules/dayzed/dist'
```
I would circle back with my thoughts on a good react datepicker but that might not be a worthy opinion until about a month from now.

**Comment by arthurdenner** [comment]
@devinrhode2, make sure you have the `v1` of `date-fns` installed. You probably have installed the `v2`, in which all the exports were modified.

**Comment by mkartchner994** [comment]
@devinrhode2 I just pushed up release candidate that has a `useDayzed` hook if you are interested in trying it out - `npm install dayzed@next`. Here is a CodeSandbox example - https://codesandbox.io/s/jolly-fog-xqk9b

After some other comments and thoughts about how to handle the `date-fns` dependency, I decided to just bundle it into the Dayzed for the RC. It doesn't add that much size to the lib and then it just leaves one less thing for people to have to worry about. @arthurdenner Let me know what you think about that.

I'll probably look to push a new major release (v3) which includes the new `useDayzed` hook and these updates for `date-fns` in the next couple days if I don't hear any big concerns.

Thanks!

**Comment by arthurdenner** [comment]
@mkartchner994, I'm fine with that.
And I see that you've bundled it with `date-fns@2` so that's even better!

**Comment by devinrhode2** [comment]
sounds like this problem is solved, and this issue can be closed.

I ended up not even using any off the shelf datepicker since our ui was only very loosely related to selecting a date anyway.

**Comment by mkartchner994** [comment]
v3 has been released. Let me know if you see any issues. Thanks!
