### ISSUE TITLE
Upgrade to use date-fns Version 2

### ISSUE THREAD

**Issue by efredine** [deseretdigital/dayzed#32]
I'd like to upgrade to version 2 of date-fns and continue using this component.

It seems like it should be relatively straight forward to update the package and fix the breaking changes. Would a pull request to do that be of interest?

**Comment by mkartchner994** [comment]
After some other comments and thoughts about how to handle the `date-fns` dependency, I decided to just bundle it into Dayzed in the release canidate that was just published (3.0.0-rc.1). This should mean you wouldn't have to worry about Dayzed anymore when upgrading `date-fns` in other parts of your app.

This RC requires react to be at >=16.8 for hooks, but still supports the `render` prop as before, so if you are already using >=16.8, it should hopefully "just work" with bumping the version.

If you wanted to try it out and let me know your thoughts that would be great . I'll probably look to push a new major release (v3) which includes the new `useDayzed` hook and these updates for `date-fns` in the next couple days if I don't hear any big concerns.

Thanks!

**Comment by efredine** [comment]
I tried it out and it does indeed 'just work' with a version bump. Thank you!

Though not essential, I'll probably refactor to use the new hook.

**Comment by mkartchner994** [comment]
v3 has been released. Let me know if you see any issues. Thanks!
