### ISSUE TITLE
Pass the event to the onDateSelected callback

### ISSUE THREAD

**Issue by arthurdenner** [deseretdigital/dayzed#34]
Hi! :wave: 

I'm trying to work on [this issue](https://github.com/arthurdenner/react-semantic-ui-datepickers/issues/30), but I can't achieve it at the moment because we are not passing the event to the `onDateSelected` callback [here](https://github.com/deseretdigital/dayzed/blob/master/src/dayzed.js#L29).

Are you in favor of adding it as a second argument (to prevent a breaking change)?

If so, I'd like to work on it :)

**Comment by arthurdenner** [comment]
@mkartchner994, do you have any thoughts on this?

**Comment by mkartchner994** [comment]
I think that makes sense. If you want to work on it that would be great. Thanks @arthurdenner

**Comment by mkartchner994** [comment]
This was released as v3.1.0 - https://github.com/deseretdigital/dayzed/releases/tag/v3.1.0

Thanks for the PR!

**Comment by arthurdenner** [comment]
Thanks for the quick approval and release! :smiley:
