### ISSUE TITLE
Unable to use useDayzed with typescript

### ISSUE THREAD

**Issue by mindsers** [deseretdigital/dayzed#36]
Thank you for your awesome work and the innovative way to handle date pickers 🎉 

Unfortunately, I'm unable to use the lib because the [types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dayzed) seem to be old enough to not export `useDayzed`.

Are them planned to be updated soon?

**Comment by mkartchner994** [comment]
Personally, I have not done much typescript, but am interested in learning it. That being said, It probably won't be in the near future. I would be willing to work with anyone who wanted to contribute types to the project though. 

Truthfully, the types in DefinitelyTyped are probably not far off. The biggest difference from 2.2 to the 3 version is that it doesn't use a class component anymore. It still is expecting the same Props and returns the same RenderProps.

Let me know if you have any interest in contributing those types. If not, I'll still leave this issue open for anyone else who might be.

Thanks for taking interest in Dayzed!

**Comment by mindsers** [comment]
I can give it a shot. I would be happy to help with that. 👍 

Should I make a PR with types to this repo or do you prefer me to update the DefinitelyTyped one ?
I have a preference for the first solution but not a strong opinion on it. 😉

**Comment by mkartchner994** [comment]
@mindsers If you wanted to make the PR to this repo, that would be great. Thanks!

**Comment by stramel** [comment]
The types have been updated in `DefinitelyTyped` to export the `useDayzed` hook. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43189

**Comment by mkartchner994** [comment]
@stramel This is awesome, thanks!

I'll close this issue for now, but @mindsers, if you are still interested in submitting a PR to add these into the repo please do so.
