### ISSUE TITLE
A possible bug in @types

### ISSUE THREAD

**Issue by scanadi** [deseretdigital/dayzed#37]
Hello i noticed that there is possible bug in Type definition for Props

![image](https://user-images.githubusercontent.com/1336058/82310307-7ee81480-99c4-11ea-86f8-3f9496326d8e.png)

Since I am trying to extend those props to my custom component, in this case the onDateSelected is requiered. So i get this error 

![image](https://user-images.githubusercontent.com/1336058/82310406-a3dc8780-99c4-11ea-963a-a753c91fe959.png)

So its a simple fix of adding a '?' to the type difinition for the onDateSelected so that its not requiered.

**Comment by mkartchner994** [comment]
Currently the `onDateSelected` is considered a required prop - https://github.com/deseretdigital/dayzed/blob/master/src/dayzed.js#L153

It could be made to be optional, but I would consider that a breaking change as the current logic that exists is expecting that function to be defined.

As a fallback, you could pass an empty function as the `onDateSelected` prop.

Let me know how you feel about something like that.

Thanks for taking interest in Dayzed!

**Comment by scanadi** [comment]
Yep thats what I did, I get the logic.

make sense thanks
