### ISSUE TITLE
How to change timezone?

### ISSUE THREAD

**Issue by winston0410** [deseretdigital/dayzed#43]
I am not able to get the correct date with dayzed, and I believe it is because of timezone issue:

```
Get current month 2020-11-19T09:17:17.952Z //got this with new Date()
checking dayzed props {
  calendars: [
    {
      firstDayOfMonth: 2020-10-31T16:00:00.000Z,
      lastDayOfMonth: 2020-11-29T16:00:00.000Z,
      month: 10,
      year: 2020,
      weeks: [Array]
    }
  ],
  getDateProps: [Function: bound getDateProps],
  getBackProps: [Function: bound getBackProps],
  getForwardProps: [Function: bound getForwardProps]
}
```

My dayzed's config:

```
      <Dayzed
        minDate={currentMonth}
        offset={0}
        firstDayofWeek={1}
        onDateSelected={(date, e) => {
          console.log('getting date', date)
        }}
        >
```

How can I fix this?

**Comment by mkartchner994** [comment]
Hello @winston0410! Thanks for the interest in Dayzed. I apologize I have been slow to respond.

From this example I am not sure which date is not correct. Dayzed just used the default browser timezone provided. I can see in the example that `firstDayOfMonth` is showing as `2020-10-31T16:00:00.000Z` which seems like the last do of October if you just looked at the date string, but if you account for the timestamp value with it it would probably be the first day of November if you were to call the appropriate functions on the Date object like `getFullYear()`, `getMonth()`(this is 0 based so would need to add 1 to it), and `getDate()`.

I don't think this is an issue with Dayzed so I am going to close this issue. If you are able to provide a reproduction of the issue or have other info you could provide please feel free to reopen this. Thanks!

**Comment by vresetnikov** [comment]
This is indeed an issue with this library, it appears that internally it does its own thing and there is no way to affect it. It is strange that a library whose main purpose is to pick a date does not have a date/ time settings, regardless if there is an issue or not.
