### ISSUE TITLE
Translate aria-labels

### ISSUE THREAD

**Issue by anton-johansson** [deseretdigital/dayzed#44]
Hey! Great library. It let me build my date picker with my UI kit without locking myself in to something that would be hard to maintain. Great work!

I would love to be able to translate the `aria-label`:
https://github.com/deseretdigital/dayzed/blob/ebf1de1ceb9695738895f8b08bf45ad9a894fe00/src/dayzed.js#L55

Maybe add support for passing in a function for back and one for forward? See suggestion in typescript definition:
```diff
 export interface Props {
   date?: Date;
   maxDate?: Date;
   minDate?: Date;
   monthsToDisplay?: number;
   firstDayOfWeek?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
   showOutsideDays?: boolean;
   selected?: Date | Date[];
   children?: RenderFn;
   render?: RenderFn;
   offset?: number;
   onOffsetChanged?(offset: number): void;
   onDateSelected(selectedDate: DateObj, event: SyntheticEvent): void;
+  getBackwardText?(offset: number): void;
+  getForwardText?(offset: number): void;
}
```

They would default to the existing values:
```ts
getBackwardText(offset: number) => {
    return `Go back ${offset} month${offset === 1 ? '' : 's'}`,
}

getForwardText(offset: number) => {
    return `Go forward ${offset} month${offset === 1 ? '' : 's'}`,
}
```

The same kind of goes for the `aria-label` for the actual date buttons:
https://github.com/deseretdigital/dayzed/blob/ebf1de1ceb9695738895f8b08bf45ad9a894fe00/src/dayzed.js#L32

... but those kind of already work because they utilize the browsers locale.

Thanks in advance!

**Comment by mkartchner994** [comment]
Thanks for the interest in Dayzed @anton-johansson!

If I understand what you are suggesting correctly, this should already be possible to do.

The getBackProps, getForwardProps, getDateProps methods will all provide default aria-labels, but each can be overridden with whatever aria-label value you provide them.

https://codesandbox.io/s/dayzed-aria-label-example-s66ok?file=/src/Single.js

In the codesandbox link above you can see an example of this on lines 34, 42, and 105. The examples also shows have you could potentially translate them to other languages using a helper function.

Let me know if there are any more questions there. Thanks!

**Comment by mkartchner994** [comment]
I am going to close this issue for now, but if the above doesn't address the problem please feel free to reopen this. Thanks!

**Comment by anton-johansson** [comment]
Yep, that did indeed work like a charm. My bad, thanks for the quick response!
