### ISSUE TITLE
[que[ - How to change date from outside of the calendar

### ISSUE THREAD

**Issue by Sparkenstein** [deseretdigital/dayzed#47]
I have a specific usecase where user should be able to change year/month by dropdowns from outside of the calendar, when dropdown changes, I want the calendar to update. I tried `setSelectedDate` (in the main example in README) but it doesn't update the calendar. 
Is this possible at the moment?

**Comment by mkartchner994** [comment]
If I understand correctly, I think you will want to use the `date` prop. Here is an example in [Codesandbox](https://codesandbox.io/s/dayzed-select-dropdown-example-5jrc4?file=/src/Single.js:4297-4336)

**Comment by Sparkenstein** [comment]
Thanks for the answer, 
iirc I tried EXACTLY same thing and it was not working for me! because it's pretty straight forward. 
maybe some version issue not sure. I will try one more time, thanks!
