### ISSUE TITLE
Is there any possibility to include time selection along with date?

### ISSUE THREAD

**Issue by srilalitharanikintali** [deseretdigital/dayzed#48]

**Comment by mkartchner994** [comment]
There are no plans to add a time component into this library but if you find something or build a library let us know and we might look to add info about those options in the README. Thanks!

**Comment by Feshchenko** [comment]
@srilalitharanikintali @mkartchner994 you can check my lib, which is also hook but has time-picker https://github.com/rehookify/datepicker
